
params = {
    "target" : "label_education_donor",
    "nw_filter": 5.5,
    "ideal_size": 183591,
    "non_ideal_size": 88191706,
    "class_balance": 2
}

include_vars = [
#     'account_id',
    'avgHouseholdAge',
    'countNumCharities',
    'countNumCharities_1year',
    'countNumCharities_3year',
    'countNumCharities_5year',
    'femaleCount',
    'hasCharityBoardMember',
    'hasCharityOfficer',
    'hasFoundationAssociation',
    'hasTrust',
    'isAnimalCause',
    'isArtsCause',
    'isBoatOwner',
    'isCharityBoardMember',
    'isCharityOfficer',
    'isCondoOwner',
    'isCoopDonation',
    'isEducationCause',
    'isEnvironmentalCause',
    'isFoundationOfficer',
    'isHouseholdDebt',
    'isHumanServicesCause',
    'isInternationalCause',
    'isMultiPropertyOwner',
    'isPlaneOwner',
    'isReligiousCause',
    'isRentalPropertyOwner',
    'isRuralResidenceOwner',
    'isSFROwner',
    'isSmallBusinessOwner',
    'isSocialBenefitCause',
#     'label',
#     'label_alternative_investment',
#     'label_education_donor',
#     'label_environment_donor',
#     'label_healthcare_donor',
#     'label_inspirato',
#     'label_insurance',
#     'label_is990Donation',
#     'label_isFECContribution',
#     'label_isHealthCause',
#     'label_isStateContribution',
#     'label_lux',
#     'label_lux_athletic',
#     'label_lux_flight',
#     'label_lux_travel',
#     'label_private_jet',
#     'label_small_business',
#     'label_tamara_mellon',
#     'label_wheelsup',
    'logAccreditedNetWorth',
    # 'logMaxDonationAmount',
    # 'logMaxDonationAmount_1year',
    # 'logMaxDonationAmount_3year',
    # 'logMaxDonationAmount_5year',
    'logMaxPropertyAvm',
    'logNetWorth',
    'logPrimaryPropertyAvm',
    # 'logSumDonationAmount',
    # 'logSumDonationAmount_1year',
    # 'logSumDonationAmount_3year',
    # 'logSumDonationAmount_5year',
    'logSumPropertyAvm',
    'logTotalHouseholdDebt',
    'logmax990Donation',
    'logmaxCOOPDonation',
    'logmaxFECDonation',
    'logmaxStateContribution',
    'logsum990Donation',
    'logsum990Donation_3year',
    'logsum990Donation_5year',
    'logsumAnimalCause',
    'logsumArtsCause',
    'logsumCOOPDonation',
    'logsumCOOPDonation_1year',
    'logsumCOOPDonation_3year',
    'logsumCOOPDonation_5year',
    'logsumEducationCause',
    'logsumEnvironmentalCause',
    'logsumFECDonation',
    'logsumFECDonation_1year',
    'logsumFECDonation_3year',
    'logsumFECDonation_5year',
    # 'logsumHealthCause',
    'logsumHumanServicesCause',
    'logsumInternationalCause',
    'logsumReligiousCause',
    'logsumSocialBenefitCause',
    'logsumStateContribution',
    'logsumStateContribution_1year',
    'logsumStateContribution_3year',
    'logsumStateContribution_5year',
    'maleCount',
    'maxBedrooms',
    'maxHouseholdAge',
    'maxPropertySqft',
    'maxPropertyYearsOwned',
    'metroNameRank',
    'metroRank',
    'minHouseholdAge',
    'minPropertyYearsOwned',
    'num_cars',
    'num_luxury_vehicles',
    'num_suvs',
    'num_trucks',
    'num_ultra_luxury_vehicles',
    'num_vans',
    'num_vehicles',
    'politicalDemocrat',
    'politicalIndependent',
    'politicalRepublican',
    'primaryPropertyLoanToValue',
    'primaryPropertySqft',
    'primaryPropertyYearsOwned',
    'propertyCount',
    'recentDeathDate',
    'recentDivorceDate',
    'recentFoundationAssociationDate',
    'recentFoundationTrusteeDate',
    'recentPhilanthropicGiftDate',
    'recentPoliticalContributionDate',
    'recentPurchaseDate',
    'recentSecTransactionAcquired',
    'recentSecTransactionDisposed',
    'stateRank',
#     'windfall_id'
]